### PR TITLE
Connection to Postgres db, create tables, insert annotations to db 

### PR DESCRIPTION
**Pull request by PauliJulia**
Connection to Postgres db, create tables, insert annotations to db and query images in utils script

### CODE REVIEW

**Review by SebastianP1997 — DISMISSED** [review]

**Comment by EvgheniiBeriozchin** [comment]
@PauliJulia can you remove the image dataset from this PR? we can then merge

**Comment by PauliJulia** [comment]
@EvgheniiBeriozchin @SebastianP1997 please check again

**Comment by EvgheniiBeriozchin** [comment]
You are deleting the data-annotations folder and adding Pauli-test.py (empty) + PyCharm cache (.idea folder).

**Comment by EvgheniiBeriozchin** [comment]
You can use the following when you're on main (!important):
git checkout -b pauli-some-purpose
git checkout Pauli -- data/connect_postgres.py
git checkout Pauli -- data/create_table.py
git checkout Pauli -- data/db_utils.py
git checkout Pauli -- annotations.py

git commit
git push

(assuming your changes lie in the Pauli branch)
* pauli-some-purpose is a placeholder.

**Comment by EvgheniiBeriozchin** [comment]
Or, on this branch do:
git checkout origin/main -- data_annotation/*
git rm Pauli_test.py
git rm .idea/*

git commit
git push

**Pull request closed without merging**
